"""3.0.1

Revision ID: 0548463664b4
Revises: a9f1c33488b6
Create Date: 2024-03-19 13:21:35.357938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0548463664b4"
down_revision: Union[str, None] = "a9f1c33488b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_Event_trip_id"), "Event", ["trip_id"], unique=False)
    op.create_index(op.f("ix_Event_vehicle_id"), "Event", ["vehicle_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Event_vehicle_id"), table_name="Event")
    op.drop_index(op.f("ix_Event_trip_id"), table_name="Event")
    # ### end Alembic commands ###
