"""6.0.5

Revision ID: 0820463fc0aa
Revises: 26166d1bc557
Create Date: 2025-01-21 22:20:20.012319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0820463fc0aa"
down_revision: Union[str, None] = "26166d1bc557"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_Event_station_id"), "Event", ["station_id"], unique=False)
    op.create_index(op.f("ix_Event_time_start"), "Event", ["time_start"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Event_time_start"), table_name="Event")
    op.drop_index(op.f("ix_Event_station_id"), table_name="Event")
    # ### end Alembic commands ###
