"""5.0.0

Revision ID: 1d0f22ea5789
Revises: 8c6c0d114d0c
Create Date: 2024-07-24 16:11:43.823929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d0f22ea5789"
down_revision: Union[str, None] = "8c6c0d114d0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Area", "row_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Area", sa.Column("row_count", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
