"""6.0.7

Revision ID: 1d60ee839397
Revises: 9415968f804e
Create Date: 2025-02-12 16:55:56.217976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d60ee839397"
down_revision: Union[str, None] = "9415968f804e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_Rotation_vehicle_id"), "Rotation", ["vehicle_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Rotation_vehicle_id"), table_name="Rotation")
    # ### end Alembic commands ###
