"""v7.1.0

Revision ID: 28528a79c8de
Revises: 7c26ba933d67
Create Date: 2025-05-06 18:09:36.460948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '28528a79c8de'
down_revision: Union[str, None] = '7c26ba933d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add table chargingpointtype
    op.create_table(
        "ChargingPointType",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("scenario_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("name_short", sa.Text(), nullable=True),
        sa.Column("tco_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["Scenario.id"],
        ),

        sa.PrimaryKeyConstraint("id"),
    )

    # Add charging point type to areas, stations and scenarios

    op.add_column(
        "Area",
        sa.Column("charging_point_type_id", sa.BigInteger(), nullable=True),
    )
    op.create_foreign_key(
        "Area_charging_point_type_id_fkey",
        "Area",
        "ChargingPointType",
        ["charging_point_type_id"],
        ["id"],
    )
    op.add_column(
        "Station",
        sa.Column("charging_point_type_id", sa.BigInteger(), nullable=True),
    )
    op.create_foreign_key(
        "Station_charging_point_type_id_fkey",
        "Station",
        "ChargingPointType",
        ["charging_point_type_id"],
        ["id"],
    )


    # Add tco parameters to vehicle type
    op.add_column(
        "VehicleType",
        sa.Column("tco_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # to battery type
    op.add_column(
        "BatteryType",
        sa.Column("tco_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # to station
    op.add_column(
        "Station",
        sa.Column("tco_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
