"""v2.2.0

Revision ID: 44aca62291a9
Revises: a06c97c98d2c
Create Date: 2024-02-14 18:16:24.916736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44aca62291a9"
down_revision: Union[str, None] = "a06c97c98d2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_Trip_arrival_time"), "Trip", ["arrival_time"], unique=False
    )
    op.create_index(
        op.f("ix_Trip_departure_time"), "Trip", ["departure_time"], unique=False
    )
    op.create_index(op.f("ix_Trip_rotation_id"), "Trip", ["rotation_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Trip_rotation_id"), table_name="Trip")
    op.drop_index(op.f("ix_Trip_departure_time"), table_name="Trip")
    op.drop_index(op.f("ix_Trip_arrival_time"), table_name="Trip")
    # ### end Alembic commands ###
