"""6.0.8

Revision ID: 747085e84b69
Revises: 1d60ee839397
Create Date: 2025-02-14 09:33:44.672904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "747085e84b69"
down_revision: Union[str, None] = "1d60ee839397"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_station_event_time_range",
        "Event",
        ["station_id", "event_type", "time_start", "time_end"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_station_event_time_range", table_name="Event")
    # ### end Alembic commands ###
