"""3.5.0

Revision ID: 8c6c0d114d0c
Revises: 0548463664b4
Create Date: 2024-07-09 16:41:43.247976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c6c0d114d0c"
down_revision: Union[str, None] = "0548463664b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Area", "vehicle_type_id", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Area", "vehicle_type_id", existing_type=sa.BIGINT(), nullable=False
    )
    # ### end Alembic commands ###
