"""v10.0.2

Revision ID: 921afffb2adf
Revises: 3a62f62ef264
Create Date: 2025-09-03 16:42:56.722730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "921afffb2adf"
down_revision: Union[str, None] = "3a62f62ef264"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Scenario", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Scenario", "description")
    # ### end Alembic commands ###
