"""6.0.6

Revision ID: 9415968f804e
Revises: 0820463fc0aa
Create Date: 2025-01-22 00:00:59.640073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9415968f804e"
down_revision: Union[str, None] = "0820463fc0aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_Event_time_start", table_name="Event")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_Event_time_start", "Event", ["time_start"], unique=False)
    # ### end Alembic commands ###
