"""5.1.7

Revision ID: 986abf14da65
Revises: 86302241f50a
Create Date: 2024-09-04 15:52:01.593839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "986abf14da65"
down_revision: Union[str, None] = "86302241f50a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ConsumptionLut",
        "columns",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),  # type: ignore
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ConsumptionLut",
        "columns",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),  # type: ignore
        nullable=True,
    )
    # ### end Alembic commands ###
