"""3.0.0

Revision ID: a9f1c33488b6
Revises: 6ac022147397
Create Date: 2024-03-18 17:31:19.584628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9f1c33488b6"
down_revision: Union[str, None] = "6ac022147397"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Area_scenario_id_name_key", "Area", type_="unique")
    op.drop_constraint("Process_scenario_id_name_key", "Process", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "Process_scenario_id_name_key", "Process", ["scenario_id", "name"]
    )
    op.create_unique_constraint(
        "Area_scenario_id_name_key", "Area", ["scenario_id", "name"]
    )
    # ### end Alembic commands ###
