"""8.2.0

Revision ID: aaf560d3e5e4
Revises: e8f748c14b93
Create Date: 2025-06-17 17:19:06.921659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aaf560d3e5e4"
down_revision: Union[str, None] = "e8f748c14b93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("Rotation", "Block")
    op.alter_column(
        table_name="Trip",
        column_name="rotation_id",
        new_column_name="block_id",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("Block", "Rotation")
    op.alter_column(
        table_name="Trip",
        column_name="block_id",
        new_column_name="rotation_id",
    )
    # ### end Alembic commands ###
