"""5.1.2

Revision ID: e232e88e379d
Revises: e85326ec1582
Create Date: 2024-08-05 19:48:50.280600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e232e88e379d"
down_revision: Union[str, None] = "e85326ec1582"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ConsumptionLut", "name", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ConsumptionLut", "name", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
