"""5.1.1

Revision ID: e85326ec1582
Revises: 3ed40e170361
Create Date: 2024-08-05 19:41:16.267992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e85326ec1582"
down_revision: Union[str, None] = "3ed40e170361"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "ConsumptionLut", ["scenario_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ConsumptionLut", type_="unique")  # type: ignore
    # ### end Alembic commands ###
